/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.flesoft.cepre.ui;

import com.flesoft.cepre.dao.UsuarioDao;
import com.flesoft.cepre.model.Usuario;
import com.flesoft.cepre.ui.util.Silk;
import com.flesoft.cepre.ui.util.TextPrompt;
import com.flesoft.cepre.util.AppContext;
import com.jgoodies.looks.plastic.PlasticLookAndFeel;
import com.jgoodies.looks.plastic.PlasticXPLookAndFeel;
import com.jgoodies.looks.plastic.theme.SkyYellow;

import com.revolsys.famfamfam.silk.SilkIconLoader;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Blob;
import java.sql.SQLException;
import java.util.List;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.ImageIcon;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;
import org.apache.shiro.SecurityUtils;
import org.apache.shiro.authc.AuthenticationException;
import org.apache.shiro.authc.ExcessiveAttemptsException;
import org.apache.shiro.authc.IncorrectCredentialsException;
import org.apache.shiro.authc.LockedAccountException;
import org.apache.shiro.authc.UnknownAccountException;
import org.apache.shiro.authc.UsernamePasswordToken;
import org.apache.shiro.subject.Subject;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Component;

/**
 *
 * @author osusr
 */
@Component
public class Login extends javax.swing.JFrame {

    private static final Logger logger = LoggerFactory.getLogger(Login.class);

    public Login() {
        initComponents();
        getRootPane().setDefaultButton(btnIngresar);
        TextPrompt placeholderDni = new TextPrompt("    DNI", txtUser);
//        placeholder.changeAlpha(0.75f);
//        placeholder.changeStyle(Font.ITALIC);
        //placeholderDni.setForeground(Color.RED);
        placeholderDni.changeAlpha(0.5f);
        placeholderDni.changeStyle(Font.ITALIC);
        placeholderDni.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/16/user.png")));

        TextPrompt placeholderPass = new TextPrompt("     Contrase\u00f1a", txtPass);
//        placeholder.changeAlpha(0.75f);
//        placeholder.changeStyle(Font.ITALIC);
        //placeholderPass.setForeground(Color.RED);
        placeholderPass.changeAlpha(0.5f);
        placeholderPass.changeStyle(Font.ITALIC);
        placeholderPass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/16/lock.png")));

        txtUser.requestFocus();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lblTitulo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        txtUser = new javax.swing.JTextField();
        txtPass = new javax.swing.JPasswordField();
        btnIngresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.SystemColor.activeCaptionBorder));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/48/key.png"))); // NOI18N

        lblTitulo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 30)); // NOI18N
        lblTitulo.setText("INGRESAR AL SISTEMA");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 14, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, java.awt.SystemColor.activeCaptionBorder));

        txtUser.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N
        txtUser.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                txtPass.requestFocusInWindow();
            }
        });

        txtPass.setFont(new java.awt.Font("Segoe UI Light", 0, 24)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE)
                    .addComponent(txtPass))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(txtPass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        btnIngresar.setFont(new java.awt.Font("Segoe UI Emoji", 0, 22)); // NOI18N
        btnIngresar.setIcon(SilkIconLoader.getIcon(Silk.KEY));
        btnIngresar.setText("Ingresar");
        btnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addComponent(btnIngresar, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnIngresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarActionPerformed
        AppContext.getInstance();
        String dni = txtUser.getText().trim();
        char[] contrasena = txtPass.getPassword();

        UsernamePasswordToken token = new UsernamePasswordToken(dni, contrasena);
        token.setRememberMe(true);
        Subject currentUser = SecurityUtils.getSubject();
        try {
            currentUser.login(token);

        } catch (UnknownAccountException uae) {

            logger.info("Auth Fallo: UnknownAccountException :" + uae.getMessage());
            JOptionPane.showMessageDialog(null, "NO existe ningun DNI: " + dni, "AVISO", JOptionPane.INFORMATION_MESSAGE);
        } catch (IncorrectCredentialsException ice) {
            logger.info("Auth Fallo: IncorrectCredentialsException :" + ice.getMessage());
            JOptionPane.showMessageDialog(null, "Contrase\u00F1a incorrecta:", "AVISO", JOptionPane.INFORMATION_MESSAGE);
        } catch (LockedAccountException lae) {
            logger.info("Auth Fallo: LockedAccountException :" + lae.getMessage());
            JOptionPane.showMessageDialog(null, "Usuario bloqueado", "AVISO", JOptionPane.INFORMATION_MESSAGE);
        } catch (ExcessiveAttemptsException eae) {
            logger.info("Auth Fallo: ExcessiveAttemptsException :" + eae.getMessage());
            JOptionPane.showMessageDialog(null, "Excesivo numero de intentos de inicio de sesion", "AVISO", JOptionPane.INFORMATION_MESSAGE);
        } catch (AuthenticationException ae) {
            logger.info("Auth Fallo: AuthenticationException :" + ae.getMessage());
        } catch (Exception e) {
            e.printStackTrace();
        }
        if (currentUser.isAuthenticated()) {
            logger.info("credenciales correctas: " + currentUser.getPrincipal());
            UsuarioDao udao = AppContext.getInstance().getBean(UsuarioDao.class); //Si ocurre un error lo indica en la consola
            //System.err.println("Error al identificar huella dactilar."+e.getMessage());
            Usuario usuario = udao.buscarPorNombre(dni);
            try {

                UIManager.setLookAndFeel(new PlasticXPLookAndFeel());//using jgoodies look
                PlasticLookAndFeel.setPlasticTheme(new SkyYellow());
                //UIManager.setLookAndFeel(new WindowsLookAndFeel());//using jgoodies look

                //UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
                //UIManager.setLookAndFeel("com.jtattoo.plaf.fast.FastLookAndFeel");
            } catch (Exception e) {

            }
            ///////////////////////////////////////////////
            final Main main = new Main();
            //main.startHttp();
            main.addWindowListener(new WindowAdapter() {
                @Override
                public void windowClosing(WindowEvent e) {
                    main.dispose();
                }
            });
            main.setVisible(true);
            dispose();
            //Si no encuentra alguna huella correspondiente al nombre lo indica con un mensaje
        }
    }//GEN-LAST:event_btnIngresarActionPerformed

    @Override
    protected JRootPane createRootPane() {
        JRootPane rootPane_ = new JRootPane();
        KeyStroke stroke = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        Action actionListener = new AbstractAction() {
            @Override
            public void actionPerformed(ActionEvent actionEvent) {
                accionCerrarVentana();
            }
        };
        InputMap inputMap = rootPane_.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(stroke, "ESCAPE");
        rootPane_.getActionMap().put("ESCAPE", actionListener);

        return rootPane_;
    }

    private void accionCerrarVentana() {
        setVisible(false);
        dispose();
    }
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Login().setVisible(true);
//            }
//        });
//    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIngresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
