/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.flesoft.cepre.ui.examen.importar;

import com.flesoft.cepre.model.Pabellon;
import com.flesoft.cepre.ui.util.TableColumnAdjuster;
import com.flesoft.cepre.util.AppContext;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.LinkedHashSet;
import java.util.List;
import com.flesoft.cepre.dao.AulaExamenDao;
import com.flesoft.cepre.dao.ExamenDao;
import com.flesoft.cepre.model.Examen;
import com.flesoft.cepre.ui.util.ProgressGlassPane;
import javax.swing.DefaultComboBoxModel;
import javax.swing.text.DefaultCaret;

/**
 *
 * @author user
 */
public class IFImportarAulas extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFImportarAulas
     */
    private JFileChooser filechoser = new JFileChooser();
    private ArrayList<Data> datas;
    private final DataTable tablaDatos = new DataTable();
    private THleerExcel leerExcel;
    private THprocesaAulasPabellones procesaAulasPabellones;
    private THprocesaEstudiantes tHprocesaEstudiantes;
    private ProgressGlassPane glassPane;

    public IFImportarAulas() {
        initComponents();
        setGlassPane(glassPane = new ProgressGlassPane());
        // ((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        DefaultCaret caret = (DefaultCaret) txtaSalida.getCaret();
        caret.setUpdatePolicy(DefaultCaret.ALWAYS_UPDATE);
        anadirTablajScrollPane();
        cargarExamenes();
    }

    private void cargarExamenes() {
        ExamenDao exd = AppContext.getInstance().getBean(ExamenDao.class);
        List<Examen> examenes = exd.listarPendientes();
        jComboBox1.setModel(new DefaultComboBoxModel(examenes.toArray()));
    }

    private void ajustarTabla() {
        TableColumnAdjuster tca = new TableColumnAdjuster(tablaDatos);
        tca.adjustColumns();
    }

    public void cargarUsuarios(List<Data> datas) {
        refrescarTablaUsuarios(datas);
    }

    public void refrescarTablaUsuarios(List<Data> datas) {
        tablaDatos.reload(datas);
    }

    private void anadirTablajScrollPane() {
        jScrollPane1.setViewportView(tablaDatos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        btnPaulaPab = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtPath = new javax.swing.JTextField();
        btnIniciar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaSalida = new javax.swing.JTextArea();

        setTitle("CARGAR DISTRIBUCION DE AULAS");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        btnPaulaPab.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        btnPaulaPab.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/24/batch.png"))); // NOI18N
        btnPaulaPab.setText("   Procesar");
        btnPaulaPab.setEnabled(false);
        btnPaulaPab.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btnPaulaPab.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaulaPabActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel1.setText("Examen:");

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 0, 18)); // NOI18N
        jLabel2.setText("Archivo:");

        txtPath.setEnabled(false);

        btnIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/16/folder.png"))); // NOI18N
        btnIniciar.setText("Examinar");
        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Salida", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        txtaSalida.setColumns(20);
        txtaSalida.setFont(new java.awt.Font("Monospaced", 0, 12)); // NOI18N
        txtaSalida.setRows(5);
        jScrollPane2.setViewportView(txtaSalida);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnIniciar))
                            .addComponent(btnPaulaPab, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 20, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIniciar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPaulaPab, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIniciarActionPerformed
        //JFileChooser fc = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("ARCHIVOS EXCEL", "xlsx");
        filechoser.setFileFilter(filter);
        int op = filechoser.showOpenDialog(this);
        if (op == JFileChooser.APPROVE_OPTION) {
            //////////////
            String path = filechoser.getSelectedFile().getPath();
            txtPath.setText(path);
            this.btnIniciar.setEnabled(false);
            getGlassPane().activate("Leyendo archivo...");
            this.leerExcel = new THleerExcel(glassPane, path, this.tablaDatos, this.btnIniciar, this.btnPaulaPab, this.txtaSalida);
            this.leerExcel.execute();

        }
    }//GEN-LAST:event_btnIniciarActionPerformed

    private void btnPaulaPabActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaulaPabActionPerformed
        //getGlassPane().activate();
        procesarAulas();
        //getGlassPane().activate();
        procesarEstudiantes();
        btnPaulaPab.setEnabled(false);
    }//GEN-LAST:event_btnPaulaPabActionPerformed

    private void procesarAulas() {
        List<Data> datass = tablaDatos.getMmodelo().getData();
        LinkedHashSet<String> pabellones = new LinkedHashSet<>();

        datass.forEach((data) -> {
            pabellones.add(data.getPabellon().trim());
            //System.out.println("::" + data.getNumero());
        });
        //System.out.println("pab: " + pabellones);
        getGlassPane().activate("Procesando pabellones y aulas...");
        this.procesaAulasPabellones = new THprocesaAulasPabellones(datass, pabellones, glassPane, btnIniciar, this.txtaSalida);
        this.procesaAulasPabellones.execute();
        //        datass.forEach((data) -> {
        //            System.out.println("aula:" + data.getAula() + " insertamos en buscar(" + data.getPabellon() + ")");
        //        });
    }

    private void procesarEstudiantes() {
        List<Data> datass = tablaDatos.getMmodelo().getData();
        Examen ex = (Examen) jComboBox1.getSelectedItem();
        long examen_id = ex.getId();
        //System.out.println("pab: " + pabellones);
        getGlassPane().activate("Procesando estudiantes...");
        this.tHprocesaEstudiantes = new THprocesaEstudiantes(datass, glassPane, examen_id, this.txtaSalida);
        this.tHprocesaEstudiantes.execute();
    }

    @Override
    public ProgressGlassPane getGlassPane() {
        return glassPane;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JButton btnPaulaPab;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txtPath;
    private javax.swing.JTextArea txtaSalida;
    // End of variables declaration//GEN-END:variables
}
