/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.flesoft.cepre.ui.personal;

import com.flesoft.cepre.ui.estudiante.*;
import com.digitalpersona.uareu.ReaderCollection;
import com.digitalpersona.uareu.UareUException;
import com.digitalpersona.uareu.UareUGlobal;
import com.flesoft.cepre.dao.ExamenDao;
import com.flesoft.cepre.model.Examen;
import com.flesoft.cepre.ui.Main;
import com.flesoft.cepre.ui.registrahuella.BuscaEstudiante;
import com.flesoft.cepre.ui.util.MessageBox;
import com.flesoft.cepre.util.AppContext;
import java.beans.PropertyVetoException;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class IFPersonal extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFEstudiantes
     */
    public IFPersonal() {
        initComponents();
        cargarIFDocentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        jXTaskPaneContainer2 = new org.jdesktop.swingx.JXTaskPaneContainer();
        pnbActualizarParametros3 = new org.jdesktop.swingx.JXTaskPane();
        jLabel6 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        contenedor = new javax.swing.JDesktopPane();

        setTitle("MODULO PERSONAL");
        setFrameIcon(null);
        setVisible(true);

        jXTaskPaneContainer2.setBackground(new java.awt.Color(240, 238, 238));
        jXTaskPaneContainer2.setBorder(null);
        jXTaskPaneContainer2.setBackgroundPainter(null);
        org.jdesktop.swingx.VerticalLayout verticalLayout1 = new org.jdesktop.swingx.VerticalLayout();
        verticalLayout1.setGap(14);
        jXTaskPaneContainer2.setLayout(verticalLayout1);

        pnbActualizarParametros3.setBackground(new java.awt.Color(240, 238, 238));
        pnbActualizarParametros3.setForeground(new java.awt.Color(51, 51, 51));
        pnbActualizarParametros3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        pnbActualizarParametros3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/24/e-learning.png"))); // NOI18N
        pnbActualizarParametros3.setTitle("PERSONAL");
        pnbActualizarParametros3.setLayout(new org.jdesktop.swingx.VerticalLayout());

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setForeground(java.awt.SystemColor.controlDkShadow);
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/16/users.png"))); // NOI18N
        jLabel6.setText("Listado de personal");
        jLabel6.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0));
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        pnbActualizarParametros3.add(jLabel6);

        jSeparator4.setForeground(new java.awt.Color(34, 34, 34));
        pnbActualizarParametros3.add(jSeparator4);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setForeground(java.awt.SystemColor.controlDkShadow);
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/16/fingerprint.png"))); // NOI18N
        jLabel7.setText("Registrar asistencia");
        jLabel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0));
        jLabel7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        pnbActualizarParametros3.add(jLabel7);

        jSeparator5.setForeground(new java.awt.Color(34, 34, 34));
        pnbActualizarParametros3.add(jSeparator5);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel8.setForeground(java.awt.SystemColor.controlDkShadow);
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/16/icons8-report-card-16.png"))); // NOI18N
        jLabel8.setText("Reporte asistencia");
        jLabel8.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 0, 5, 0));
        jLabel8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        pnbActualizarParametros3.add(jLabel8);

        jXTaskPaneContainer2.add(pnbActualizarParametros3);

        jSplitPane2.setLeftComponent(jXTaskPaneContainer2);

        javax.swing.GroupLayout contenedorLayout = new javax.swing.GroupLayout(contenedor);
        contenedor.setLayout(contenedorLayout);
        contenedorLayout.setHorizontalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 649, Short.MAX_VALUE)
        );
        contenedorLayout.setVerticalGroup(
            contenedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );

        jSplitPane2.setRightComponent(contenedor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked

        cargarIFAsistencia();
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        cargarIFDocentes();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        carcarIFreportes();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void carcarIFreportes() {
        limpiarFrames();
        IFAPersonal demo = new IFAPersonal();
//        demo.setParentFrame(this);
        this.contenedor.add(demo);
        try {
            demo.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        demo.show();
    }

    private void cargarIFAsistencia() {
        if (!checkReader()) {
            return;
        }
        limpiarFrames();
        ExamenDao examenDao = AppContext.getInstance().getBean(ExamenDao.class);

        //TaskDialogs.warning(null, "Importante!", "Ningun examen programado para hoy");
        List<Examen> examenes = examenDao.listarPendientes();
        Object[] choices = examenes.toArray();
        Examen examen_ = (Examen) JOptionPane.showInputDialog(null,
                "POR FAVOR SELECCIONE UN EXAMEN",
                "NO SE ENCONTRO NINGUN EXAMEN", JOptionPane.INFORMATION_MESSAGE, null,
                choices, // Array
                null); // Valor Inicial
        System.out.println(examen_);
        if (examen_ == null) {
            return;
        }

        IFAsistenciaPersonal demo = new IFAsistenciaPersonal(examen_);
//        demo.setParentFrame(this);
        this.contenedor.add(demo);
        try {
            demo.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        demo.show();
    }

    private void cargarIFDocentes() {
        limpiarFrames();

        IFIPersonal iFusuarios = new IFIPersonal();
        //        iFusuarios.setMainFrame(this);
        this.contenedor.add(iFusuarios);
        try {
            iFusuarios.setMaximum(true);
        } catch (PropertyVetoException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        iFusuarios.show();
    }

    private void limpiarFrames() {
        JInternalFrame[] frames = contenedor.getAllFrames();
        for (JInternalFrame f : frames) {
            f.dispose();
        }
        contenedor.removeAll();
        contenedor.updateUI();
        revalidate();
        repaint();
    }

    protected boolean checkReader() {
        try {
            ReaderCollection m_collection = UareUGlobal.GetReaderCollection();
            m_collection.GetReaders();
            if (m_collection.isEmpty()) {
                MessageBox.Warning("No se detecto ningun Lector, por favor conecte el lector de huellas antes...");
                return false;
            }
        } catch (UareUException e1) {
            // TODO Auto-generated catch block
            JOptionPane.showMessageDialog(null, "Error getting collection");
            return false;
        }

        return true;
//        m_reader = m_collection.get(0);
//
//        if (null == m_reader) {
//            MessageBox.Warning("Lector no conectado?");
//        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane contenedor;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSplitPane jSplitPane2;
    private org.jdesktop.swingx.JXTaskPaneContainer jXTaskPaneContainer2;
    private org.jdesktop.swingx.JXTaskPane pnbActualizarParametros3;
    // End of variables declaration//GEN-END:variables
}
