/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.flesoft.cepre.ui.registrahuella;

import com.digitalpersona.uareu.Fmd;
import com.digitalpersona.uareu.Reader;
import com.digitalpersona.uareu.ReaderCollection;
import com.flesoft.cepre.ui.registrahuella.DLGRegistraHuella;
import com.flesoft.cepre.ui.util.ErrorDialog;
import com.flesoft.cepre.dao.EstudianteDao;
import com.flesoft.cepre.model.Aula;
import com.flesoft.cepre.model.AulaEstudiante;
import com.flesoft.cepre.model.Estudiante;
import com.flesoft.cepre.model.Pabellon;
import com.flesoft.cepre.model.Sede;
import com.flesoft.cepre.ui.Main;
import com.flesoft.cepre.ui.util.FiltroNumeros;
import com.flesoft.cepre.util.AppContext;
import com.flesoft.cepre.util.Config;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import javax.swing.AbstractAction;
import javax.swing.Action;
import javax.swing.InputMap;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import javax.swing.JRootPane;
import javax.swing.KeyStroke;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/**
 *
 * @author edrev
 */
public class BuscaEstudiante extends javax.swing.JInternalFrame {

    private static final Log logger = LogFactory.getLog(BuscaEstudiante.class);
    private Main parentFrame;

    private ReaderCollection m_collection;
    private Reader m_reader;
    private Fmd enrollmentFMD;

    public BuscaEstudiante() {
        initComponents();
        //((javax.swing.plaf.basic.BasicInternalFrameUI) this.getUI()).setNorthPane(null);
        getRootPane().setDefaultButton(btnBuscar);
        txtDNI.setDocument(new FiltroNumeros(txtDNI, 8));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        txtDNI = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();

        setTitle("REGISTRAR HUELLA");

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPanel2KeyPressed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "BUSCAR ALUMNO", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI Light", 1, 48)); // NOI18N
        jLabel3.setText("DNI:");

        txtDNI.setFont(new java.awt.Font("Segoe UI Light", 1, 45)); // NOI18N
        txtDNI.setText("74301550");
        txtDNI.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDNIFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDNIFocusLost(evt);
            }
        });

        btnBuscar.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        btnBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/32/Search-32.png"))); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtDNI, javax.swing.GroupLayout.DEFAULT_SIZE, 361, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDNI, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(249, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void buscarEstudiante() {
        try {
            System.out.println("##Buscando##");
            String dni = txtDNI.getText().trim();

            EstudianteDao estudianteDao = AppContext.getInstance().getBean(EstudianteDao.class);
            Estudiante estudiante = estudianteDao.buscarPorDni(dni);
            System.out.println("est:" + estudiante);
            if (estudiante == null) {
                JOptionPane.showMessageDialog(this, "No se encuentra ningun estudiante con el dni: " + dni, "AVISO", JOptionPane.WARNING_MESSAGE);
                return;
            }
            //comprobar que aun no se registro
            //boolean existe = estudianteDao.existeHuellaCiclo(estudiante.getId());

            AulaEstudiante aulaEstudiante = estudianteDao.buscarAula(estudiante.getId());
            if (aulaEstudiante == null) {
                JOptionPane.showMessageDialog(this, estudiante.getCompleto() + " No esta asignado a ningun aula ", "Aviso", JOptionPane.WARNING_MESSAGE);
                return;
            }
            boolean existe = aulaEstudiante.getHuella() != null;
            if (existe) {
                int dialogResult = JOptionPane.showConfirmDialog(this,
                        "Ya se registro huella para el estudiante: " + estudiante.getCompleto() + "\n"
                        + "DESEA ACTUALIZAR LA HUELLA?",
                        "Aviso",
                        JOptionPane.YES_NO_OPTION);
                if (dialogResult == JOptionPane.YES_OPTION) {
                    Aula aula = aulaEstudiante.getAula();
                    Pabellon pabellon = aula.getPabellon();

                    String turno = aulaEstudiante.getTurno().equals("m") ? "Ma\u00F1ana" : "Tarde";
                    Sede sede = aulaEstudiante.getAula().getPabellon().getSede();
                    logger.info("estudiante: " + estudiante);
                    logger.info("aulaEstudiante: " + aulaEstudiante);
                    logger.info("sede: " + sede);
                    logger.info("aula: " + aula);
                    logger.info("pabellon: " + pabellon);
                    logger.info("Turno: " + turno);
                    lanzarDialogEstudiante(aulaEstudiante);
                } else {
                    return;
                }

//                JOptionPane.showMessageDialog(this, "Ya se registro huella para el estudiante: " + estudiante.getCompleto(), "Aviso", JOptionPane.WARNING_MESSAGE);
//                return;
            } else {
                lanzarDialogEstudiante(aulaEstudiante);
            }

            //Si no encuentra alguna huella correspondiente al nombre lo indica con un mensaje
        } catch (NullPointerException npe) {
//            JOptionPane.showMessageDialog(this, npe, "AVISO", JOptionPane.INFORMATION_MESSAGE);
            npe.printStackTrace();
            new ErrorDialog("Error", "Excepcion no controlada", npe);

        } catch (Exception e) {
            //JOptionPane.showMessageDialog(this, e, "AVISO", JOptionPane.INFORMATION_MESSAGE);
            e.printStackTrace();
            new ErrorDialog("Error", "Excepcion no controlada", e);

        }
        System.out.println(" fin ##Buscando##");
    }
    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        buscarEstudiante();

    }//GEN-LAST:event_btnBuscarActionPerformed

    private void txtDNIFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDNIFocusGained
        // TODO add your handling code here:
        logger.info("recuepere el foco");
        txtDNI.selectAll();
    }//GEN-LAST:event_txtDNIFocusGained

    private void txtDNIFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDNIFocusLost
        // TODO add your handling code here:
        logger.info("perdi el foco");
    }//GEN-LAST:event_txtDNIFocusLost

    private void jPanel2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPanel2KeyPressed
        // TODO add your handling code here:
        logger.info("Se presiono la tecla: " + evt.toString());

    }//GEN-LAST:event_jPanel2KeyPressed

    private void lanzarDialogEstudiante(AulaEstudiante aulaEstudiante) {

        this.enrollmentFMD = DLGRegistraHuella.Run(aulaEstudiante);

//        DLGRegistraHuella dialog = new DLGRegistraHuella();
//        dialog.setAulaEstudiante(aulaEstudiante);
//        dialog.setParentFrame(getParentFrame());
//        dialog.setVisible(true);
    }

    protected JRootPane createRootPane() {
        JRootPane rootPane = new JRootPane();
        KeyStroke stroke = KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0);
        Action actionListener = new AbstractAction() {
            public void actionPerformed(ActionEvent actionEvent) {
                logger.info("Se presiono la tecla: ESCAPE");
                txtDNI.requestFocus();
                txtDNI.selectAll();
            }
        };
        InputMap inputMap = rootPane.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW);
        inputMap.put(stroke, "ESCAPE");
        rootPane.getActionMap().put("ESCAPE", actionListener);
        return rootPane;
    }

    /**
     * @return the parentFrame
     */
    public Main getParentFrame() {
        return parentFrame;
    }

    /**
     * @param parentFrame the parentFrame to set
     */
    public void setParentFrame(Main parentFrame) {
        this.parentFrame = parentFrame;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtDNI;
    // End of variables declaration//GEN-END:variables

}
