/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.flesoft.cepre.ui.estudiante;

/**
 *
 * @author user
 */
public class Template extends javax.swing.JInternalFrame {

    /**
     * Creates new form IFEstudiantes
     */
    public Template() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        jXTaskPaneContainer2 = new org.jdesktop.swingx.JXTaskPaneContainer();
        pnbActualizarParametros1 = new org.jdesktop.swingx.JXTaskPane();
        jLabel2 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();

        jXTaskPaneContainer2.setBackground(new java.awt.Color(240, 238, 238));
        jXTaskPaneContainer2.setBorder(null);
        jXTaskPaneContainer2.setBackgroundPainter(null);
        jXTaskPaneContainer2.setLayout(new java.awt.BorderLayout());

        pnbActualizarParametros1.setBackground(new java.awt.Color(240, 238, 238));
        pnbActualizarParametros1.setForeground(new java.awt.Color(51, 51, 51));
        pnbActualizarParametros1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        pnbActualizarParametros1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/24/e-learning.png"))); // NOI18N
        pnbActualizarParametros1.setTitle("ESTUDIANTES             ");
        pnbActualizarParametros1.setLayout(new org.jdesktop.swingx.VerticalLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Semibold", 0, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/24/fingerprint_scanner.png"))); // NOI18N
        jLabel2.setText("Registrar huella");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 0, 0, 0, java.awt.SystemColor.activeCaptionBorder));
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        pnbActualizarParametros1.add(jLabel2);

        jXTaskPaneContainer2.add(pnbActualizarParametros1, java.awt.BorderLayout.PAGE_START);

        jSplitPane2.setLeftComponent(jXTaskPaneContainer2);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 649, Short.MAX_VALUE)
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 533, Short.MAX_VALUE)
        );

        jSplitPane2.setRightComponent(jDesktopPane1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSplitPane jSplitPane2;
    private org.jdesktop.swingx.JXTaskPaneContainer jXTaskPaneContainer2;
    private org.jdesktop.swingx.JXTaskPane pnbActualizarParametros1;
    // End of variables declaration//GEN-END:variables
}
